services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Volume para persistir as mensagens

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: sistema_certificado
    volumes:
      - ~/mysqldata:/var/lib/mysql
      - ./db-mysql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql 
    ports:
      - "3306:3306"

  worker-certificate:
    build:
      context: ./worker/Api.Processor
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - pdf_data:/app/pdfs
      - ./worker/CertificateTemplate/certificate.html:/app/templates

  api-certificate:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=sistema_certificado
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123
      

volumes:
  mysqldata:
  rabbitmq_data:
  pdf_data:
